import { Lead, LeadInput } from '../types';

export async function analyzeSingleLeadApi(input: LeadInput): Promise<Lead> {
  try {
    const res = await fetch('/api/analyze', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ lead: input }),
    });

    const data = await res.json();
    if (data && data.result) {
      const r = data.result;
      const score = typeof r.lead_score === 'number' ? r.lead_score : 50;
      
      const initials = (input.fullName || 'New Lead')
        .split(' ')
        .map((n) => n[0])
        .join('')
        .toUpperCase()
        .slice(0, 2) || 'NL';

      const tierColors = {
        Hot: { bg: 'bg-[#006b2c]/10', text: 'text-[#006b2c]' },
        Warm: { bg: 'bg-[#10B981]/10', text: 'text-[#10B981]' },
        Cold: { bg: 'bg-[#EAB308]/10', text: 'text-[#B45309]' },
        'Very Low': { bg: 'bg-[#94A3B8]/10', text: 'text-[#64748B]' },
      };

      const tierKey = (r.tier as keyof typeof tierColors) || (score >= 90 ? 'Hot' : score >= 70 ? 'Warm' : 'Cold');
      const colorScheme = tierColors[tierKey] || tierColors['Cold'];

      return {
        ...input,
        id: `lead-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
        rank: 1,
        score,
        fitScore: r.fit_score || (score >= 80 ? 'Excellent' : 'Good'),
        intentScore: r.intent || (score >= 70 ? 'High' : 'Medium'),
        tier: tierKey,
        summary: r.summary || 'Lead qualification generated by Gemini AI.',
        reasoning: Array.isArray(r.reasoning) ? r.reasoning : ['Evaluated by Gemini AI engine'],
        nextAction: r.next_action || 'Follow up with prospect',
        factorBreakdown: r.factor_breakdown || {
          budgetAvailability: Math.min(20, Math.round(score * 0.2)),
          buyingIntent: Math.min(25, Math.round(score * 0.25)),
          companySize: Math.min(10, Math.round(score * 0.1)),
          decisionMaker: Math.min(15, Math.round(score * 0.15)),
          timelineUrgency: Math.min(15, Math.round(score * 0.15)),
          industryFit: Math.min(10, Math.round(score * 0.1)),
          requirementClarity: Math.min(5, Math.round(score * 0.05)),
        },
        avatarInitials: initials,
        avatarBg: colorScheme.bg,
        avatarTextColor: colorScheme.text,
        createdAt: new Date().toISOString().split('T')[0],
      };
    }
  } catch (err) {
    console.warn('API call failed, generating client fallback evaluation:', err);
  }

  // Fallback calculation if fetch fails
  const score = calculateLocalScore(input);
  const tier = score >= 90 ? 'Hot' : score >= 70 ? 'Warm' : score >= 40 ? 'Cold' : 'Very Low';
  return {
    ...input,
    id: `lead-local-${Date.now()}`,
    rank: 1,
    score,
    fitScore: score >= 80 ? 'Excellent' : 'Good',
    intentScore: score >= 70 ? 'High' : 'Medium',
    tier: tier as any,
    summary: `${input.fullName || 'Lead'} from ${input.company || 'Company'} evaluated with score ${score}/100.`,
    reasoning: [
      `Role '${input.jobTitle || 'Contact'}' evaluated for decision power`,
      `Budget '${input.budget || 'Unspecified'}' analyzed for feasibility`,
      `Requirements '${input.requirements || 'Inquiry'}' evaluated for fit`
    ],
    nextAction: score >= 90 ? 'Schedule Executive Demo' : score >= 70 ? 'Send Proposal' : 'Share Product Information',
    factorBreakdown: {
      budgetAvailability: Math.min(20, Math.round(score * 0.2)),
      buyingIntent: Math.min(25, Math.round(score * 0.25)),
      companySize: 8,
      decisionMaker: 12,
      timelineUrgency: 12,
      industryFit: 8,
      requirementClarity: 4,
    },
    avatarInitials: (input.fullName || 'NL').split(' ').map((n) => n[0]).join('').slice(0, 2).toUpperCase(),
    avatarBg: 'bg-[#006b2c]/10',
    avatarTextColor: 'text-[#006b2c]',
    createdAt: new Date().toISOString().split('T')[0],
  };
}

function calculateLocalScore(input: LeadInput): number {
  let score = 50;
  const role = (input.jobTitle || '').toLowerCase();
  const text = `${input.fullName} ${input.company} ${input.budget} ${input.requirements} ${input.notes}`.toLowerCase();

  if (role.includes('ceo') || role.includes('cto') || role.includes('c-') || role.includes('vp') || role.includes('founder') || role.includes('director') || role.includes('head')) {
    score += 25;
  }
  if (text.includes('$100') || text.includes('$120') || text.includes('$80') || text.includes('100k') || text.includes('approved')) {
    score += 20;
  }
  if (text.includes('urgent') || text.includes('2 weeks') || text.includes('demo') || text.includes('proposal')) {
    score += 15;
  }

  return Math.min(Math.max(score, 30), 98);
}
